services:
  redis:
    image: redis:7.2
    container_name: redis-container
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend-network
    restart: always
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

volumes:
  redis-data:
    driver: local

networks:
  backend-network:
    driver: bridge
