spring:
  application:
    name: sns1_server
  config:
    import:
        - optional:file:.env[.properties]
        - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_db.yml
        - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_server.yml
        - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_auth.yml
        - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_docs.yml
  profiles:
    group:
        dev: [ "dev_db" ]
        prod: [ "prod_db" ]
    active: dev
