spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
custom:
  jwt:
    access-token:
      expiration-time: 1h # 1hour
      secret: ${JWT_ACCESS_TOKEN_SECRET_KEY}
    refresh-token:
      expiration-time: 30d # 30days
      secret: ${JWT_REFRESH_TOKEN_SECRET_KEY}
