ALTER TABLE follow
DROP
FOREIGN KEY FK_FOLLOW_ON_REQUESTER;

ALTER TABLE follow
DROP
FOREIGN KEY FK_FOLLOW_ON_TARGET;

ALTER TABLE follow
    ADD follower_id BIGINT NULL;

ALTER TABLE follow
    ADD following_id BIGINT NULL;

ALTER TABLE follow
    MODIFY follower_id BIGINT NOT NULL;

ALTER TABLE follow
    MODIFY following_id BIGINT NOT NULL;

ALTER TABLE follow
    ADD CONSTRAINT FK_FOLLOW_ON_FOLLOWER FOREIGN KEY (follower_id) REFERENCES member (id);

ALTER TABLE follow
    ADD CONSTRAINT FK_FOLLOW_ON_FOLLOWING FOREIGN KEY (following_id) REFERENCES member (id);

ALTER TABLE follow
DROP
COLUMN requester_id;

ALTER TABLE follow
DROP
COLUMN target_id;
